### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by stephen-crawford** [opensearch-project/search-processor#104]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the Search Processor repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Search Processor | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | Certificate of Origin, Link Checker, Create Documentation Issue  | https://github.com/opensearch-project/search-processor/issues/104 | 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by macohen** [comment]
This repo is not in a distribution yet. Can you say more about requirements for code coverage? Is this referring to codecov.yml?

**Comment by stephen-crawford** [comment]
Hi @macohen, thank you for the follow-up sorry I was not more aware of the timeline. There are not any specific requirements for code coverage, I just was not sure if you had any type of repo standards you enforced or planned to.

**Comment by FredaProMax** [comment]
This repo has codecov https://app.codecov.io/gh/opensearch-project/search-processor

> I don't see any requirements for code coverage in the testing documentation.

@scrawfor99 What document are you referring to, and is there a best practice / template we can follow?

**Comment by noCharger** [comment]
This repo has codecov https://app.codecov.io/gh/opensearch-project/search-processor

> I don't see any requirements for code coverage in the testing documentation.

@scrawfor99 What document are you referring to, and is there a best practice / template we can follow?

**Comment by stephen-crawford** [comment]
Hi @noCharger, thank you for following up. Sorry I missed that before. I was not referring to any specific document, I just meant the repository documentation. For instance, if your README had any sort guidelines you asked people to follow. I will update the notes for the repository. Thanks you.

**Comment by noCharger** [comment]
Sure we can add more guidelines. This is what we have so far https://github.com/opensearch-project/search-processor/blob/main/DEVELOPER_GUIDE.md#backwards-compatibility-testing

> Hi @noCharger, thank you for following up. Sorry I missed that before. I was not referring to any specific document, I just meant the repository documentation. For instance, if your README had any sort guidelines you asked people to follow. I will update the notes for the repository. Thanks you.

**Comment by macohen** [comment]
We'll add one line to the README to aim for test coverage at over 80%.

**Comment by msfroh** [comment]
We now have a `codecov` GitHub action that will fail checks if changes don't have sufficient test coverage.
