### ISSUE TITLE
[PROPOSAL] List options to choose an enhanced/modified search API for OpenSearch

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/search-processor#11]
### What are you proposing?
_In a few sentences, describe the feature and its core capabilities._

### How did you come up with this proposal?
_Highlight any research, proposals, requests, issues, forum posts, anecdotes that signal this is the right thing to build. Highlight opportunities for additional research._

### What is the user experience going to be?
_Describe the feature requirements and or user stories. You may include low-fidelity sketches, wireframes, APIs stubs, or other examples of how a user would use the feature. Using a bulleted list or simple diagrams to outline features is okay. e.g. As a < type of user > , I want to < achieve a goal > so that < for some reason >._

### Why should it be built? Any reason not to?
_Describe the most important user needs, pain points, and the value that this feature will bring to the OpenSearch community, as well as what impact it has if it isn't built, or new risks if it is. What is preventing you from meeting this need today?_

### What will it take to execute?
_Describe what it will take to build this feature. Are there any assumptions you may be making that could limit scope or add limitations? Are there performance, cost, or technical constraints that may impact the user experience? Does this feature depend on other feature work? What additional risks are there?_

### What are remaining open questions?
_List questions that may need to be answered before proceeding with an implementation._

**Comment by macohen** [comment]
Is there more to say about this or other issues that supersede this one? Should it be closed out?

**Comment by macohen** [comment]
Closing with no additional info.
