### ISSUE TITLE
Prevent Personalize ranking processor from being created as part of an ad hoc pipeline

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/search-processor#182]
In https://github.com/opensearch-project/OpenSearch/issues/8163, we made a change to pass the pipeline creation context to a processor factory, so the factory can take appropriate action depending on how it's being called.

For the Personalize ranking processor, we should fail if invoked as part of a search request (i.e. in an ad hoc pipeline), to make sure that we're not creating a new AWS Personalize client on every search request. This requires a check in the Personalize processor factory.

**Comment by noCharger** [comment]
We will create the new release candidate 2.9.0.1 for this fix.

**Comment by mingshl** [comment]
updated the artifact link [here](https://github.com/opensearch-project/search-processor/releases/download/2.9.0/opensearch-search-processor-2.9.0.0.zip)
