### ISSUE TITLE
[FEATURE] Windows Support

### ISSUE THREAD

**Issue by macohen** [opensearch-project/search-processor#19]
### Is your feature request related to a problem?
All OpenSearch plugins must support Windows.

### What solution would you like?
The in repo-CI build for the plugin passes on Windows

### What alternatives have you considered?
None.

### Do you have any additional context?
[logs_15.zip](https://github.com/opensearch-project/search-relevance/files/9952640/logs_15.zip)
It looks like the AWS config either needs to be mocked or configured correctly 
The workflow was copied from the k-NN repo.

**Comment by msfroh** [comment]
I think we enabled Windows builds. I remember having to fix an integration test that was failing on Windows.

**Comment by noCharger** [comment]
> I think we enabled Windows builds. I remember having to fix an integration test that was failing on Windows.

@msfroh Shall we close this one with the action items linked?
