### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/search-processor#31]
This project currently (November 22, 2022) has around 21% line coverage from tests. 

We should increase that significantly to get more confidence on future changes (and maybe uncover some lurking bugs along the way).

I'm going to suggest a target of 80% before we can call this issue "done".

**Comment by noCharger** [comment]
https://app.codecov.io/gh/opensearch-project/search-processor/tree/main/src/main/java/org/opensearch/search/relevance?displayType=list

Top priorities
1. https://app.codecov.io/gh/opensearch-project/search-processor/blob/main/src/main/java/org/opensearch/search/relevance/configuration/SearchConfigurationExtBuilder.java - 14.04%
2. https://app.codecov.io/gh/opensearch-project/search-processor/tree/main/src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/model - low coverage on data models
3. https://app.codecov.io/gh/opensearch-project/search-processor/tree/main/src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/client - missing test in client

Full list of under 80% coverage



src/main/java/org/opensearch/search/relevance/SearchRelevancePlugin.java | 11 | 0 | 0 | 11 | 0.00%
-- | -- | -- | -- | -- | --
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/client/KendraHttpClient.java | 42 | 0 | 0 | 42 | 0.00%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/client/KendraClientSettings.java | 38 | 0 | 0 | 38 | 0.00%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/client/SimpleAwsErrorHandler.java | 7 | 0 | 0 | 7 | 0.00%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/client/SimpleResponseHandler.java | 3 | 0 | 0 | 3 | 0.00%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/model/KendraIntelligentRankingException.java | 8 | 0 | 0 | 8 | 0.00%
src/main/java/org/opensearch/search/relevance/configuration/SearchConfigurationExtBuilder.java | 57 | 8 | 0 | 49 | 14.04%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/configuration/KendraIntelligentRankingConfiguration.java | 99 | 34 | 0 | 65 | 34.34%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/model/dto/Document.java | 22 | 8 | 0 | 14 | 36.36%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/model/dto/RescoreRequest.java | 10 | 5 | 0 | 5 | 50.00%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/model/dto/RescoreResult.java | 7 | 4 | 0 | 3 | 57.14%
src/main/java/org/opensearch/search/relevance/transformer/TransformerType.java | 10 | 6 | 0 | 4 | 60.00%
src/main/java/org/opensearch/search/relevance/configuration/ConfigurationUtils.java | 27 | 18 | 6 | 3 | 66.67%
src/main/java/org/opensearch/search/relevance/configuration/TransformerConfiguration.java | 6 | 4 | 0 | 2 | 66.67%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/KendraIntelligentRanker.java | 101 | 68 | 13 | 20 | 67.33%
src/main/java/org/opensearch/search/relevance/transformer/ResultTransformerType.java | 10 | 7 | 2 | 1 | 70.00%
src/main/java/org/opensearch/search/relevance/transformer/kendraintelligentranking/configuration/KendraIntelligentRankerSettings.java | 30 | 23 | 0 | 7 | 76.67%
src/main/java/org/opensearch/search/relevance/client/OpenSearchClient.java | 9 | 7 | 1 | 1 | 77.78%
