### ISSUE TITLE
Refactor metrics and logging

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/search-processor#44]
This is the follow up of https://github.com/opensearch-project/search-processor/pull/38

From @macohen: "We do want to review the full set of metrics and logging events to capture. We'll create another issue for that purpose."

**Comment by macohen** [comment]
For the Search Pipelines release, what metrics are we logging/exposing?

What should we provide in pipelines? What should processor builders be responsible for?
Some suggestions:
- [ ] A Common Logging Format for All Pipelines (compatible with user behavior logging?)
- [ ] Total Processor Latency
- [ ] Network Call Latency Within Processor (if any)

**Comment by msfroh** [comment]
Regarding search pipelines (which is not in this repo), we have https://github.com/opensearch-project/OpenSearch/issues/6723.

Assuming we follow the description in that issue, we would effectively copy https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/ingest/IngestStats.java

Following that model, the stats effectively form a 2D matrix. In one dimension, we have total time, total execution count, failure count, and active execution count (i.e. how many requests are executing *right now*). In the other dimension, we have stats for all pipelines, stats for each pipeline, and stats for each processor (across all processors).

**Comment by macohen** [comment]
Duplicates opensearch-project/OpenSearch#6723
