### ISSUE TITLE
[CI] Add integration test and BWC test

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/search-processor#46]
Add integration test and BWC test

**Comment by macohen** [comment]
@noCharger Do we still need this? If we're planning to build the search pipeline into core then this may just become the Kendra plugin which may still be needed, but I want to check on this. I don't believe this is needed for a 2.6 release though given that we're working towards a 2.7 release for search pipelines.

**Comment by noCharger** [comment]
Close this issue due to no current plan. Feel free to open it in the future.
