### ISSUE TITLE
[Doc] Add API reference

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/search-processor#47]
This repo should include documentation that explains all possible parameters for the available result transformers.

As we reimplement result transformers as search pipeline processors (see e.g. https://github.com/opensearch-project/OpenSearch/issues/7158, which probably belongs in this repo, not in OpenSearch core), we will need to update the documentation.

**Comment by macohen** [comment]
Can you be more specific with the APIs to document? Is this going to be covered by search pipelines?

**Comment by macohen** [comment]
@noCharger is your original request satisfied? If not, what's left? The process to update docs for users is to create an issue in #opensearch-project/documentation-website.

**Comment by noCharger** [comment]
Close this issue since API references are updated https://opensearch.org/docs/latest/search-plugins/search-pipelines/index/
