### ISSUE TITLE
Onboard to OpenSearch build distribution for release

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/search-processor#52]
Since we want to release in 2.5, there are a few things we should double-check:

https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md
https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md

**Comment by noCharger** [comment]
Moved to 2.6 for now

**Comment by macohen** [comment]
@msfroh will we onboard this repo for search pipelines?

**Comment by noCharger** [comment]
No AI for now. Free to open in the future
