### ISSUE TITLE
[BUG] flowwer-dev/pull-request-stats: Resource not accessible by integration

### ISSUE THREAD

**Issue by macohen** [opensearch-project/search-processor#66]
**What is the bug?**
I have an issue where I’m trying to integrate a github action (https://github.com/flowwer-dev/pull-request-stats) that should add a comment with PR stats to every PR. I’ve been trying to make it work with PRs opened against main, but it was failing due to permissions (https://github.com/opensearch-project/search-processor/actions/runs/3766987233/jobs/6404075146). I also created two branches in the repo and made a PR from one to the other. That one succeeded: (https://github.com/opensearch-project/search-processor/pull/62). It’s strange to me that a PR to main would have different permissions than a PR to a different branch and I'm not sure where to go from there.

**How can one reproduce the bug?**
1. Enable the (Pull Request Stats)[https://github.com/opensearch-project/search-processor/actions/workflows/pr_stats.yml]
2. Create a PR to merge to main
3. Watch the check fail like in: https://github.com/opensearch-project/search-processor/actions/runs/3766987233

**What is the expected behavior?**
A comment should be added to the PR like https://github.com/opensearch-project/search-processor/pull/62#issuecomment-1364081738

**What is your host/environment?**
N/A

**Do you have any screenshots?**
No, but the logfile with error is here: [logs_561.zip](https://github.com/opensearch-project/search-processor/files/10297446/logs_561.zip)

**Do you have any additional context?**
Add any other context about the problem.

**Comment by macohen** [comment]
@manuelmhtr unfortunately that didn't seem to do the trick. is there a different setting? thanks for the quick response on this!

**Comment by manuelmhtr** [comment]
@macohen ohh I see...

I checked the last run and it seems the pull request permission still `read`. I think there's an organization or repository setting that prevents the action from getting the `read` permission. Let me check which setting could be 🤔 

![Screen Shot 2022-12-23 at 17 33 07](https://user-images.githubusercontent.com/1031639/209413395-deafb75f-be3e-45b5-af05-4721aae140b8.png)

**Comment by manuelmhtr** [comment]
I found the problem 💡 

All failing jobs come from a fork. By default, Github limits the action's permissions to `read` when they come from a fork.

To make it work you should go to the `Organization Settings` -> `Actions` -> `General`, and check the options "Run workflows from fork pull requests" and "Send write tokens to workflows from fork pull requests." (I'd suggest "Require approval for fork pull request workflows." too for increasing security).

![Screen Shot 2022-12-23 at 17 52 09](https://user-images.githubusercontent.com/1031639/209414256-70c3bb27-588f-4142-a17a-9e52bf438a4c.png)

I hope it helps!

**Comment by macohen** [comment]
@manuelmhtr Do you think it would be possible to create an alternative solution to work around this? I'm thinking about a scheduled action that creates a new issue in the repo with the table. It would be great to see this on a weekly basis. Maybe also aggregated monthly.

**Comment by noCharger** [comment]
PR stats works in 2.x branch https://github.com/opensearch-project/search-processor/pull/76#issuecomment-1371297111

**Comment by macohen** [comment]
yep. it doesn't seem to work for pull requests coming from forked repositories because that would mean giving certain write permissions to anyone who forks the repo and issues a PR. if you branch within the repo it works. I still like the idea of a report in an issue that can be viewed separately.

**Comment by msfroh** [comment]
We could run only on backport PRs?

We can also come up with another way of tracking / recording PR stats.

Closing this one in favor of finding another solution.

**Comment by manuelmhtr** [comment]
@macohen @msfroh sorry for the ultra-late response.

You could configure the action to be executed periodically and post the results in [Slack](https://github.com/flowwer-dev/pull-request-stats/blob/master/docs/slack.md), [MS Teams](https://github.com/flowwer-dev/pull-request-stats/blob/master/docs/teams.md) or publish the results to a [webhook](https://github.com/flowwer-dev/pull-request-stats/blob/master/docs/webhook.md) and threat the response however you want. This way you should not get the permissions error when writing on the pull request.

I added OpenSearch as a private sponsor to let you use these premium features for free (use `v2.7.1` or above).

Hope it helps!
