### ISSUE TITLE
[RFC] OpenSearch Simple Schema : Search

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/search-processor#7]
## **Why Use a Schema?**
Schema is a means to address the problems of managing and handling unstructured or loosely structured data, in opensearch we need to address the following concerns regarding the stored data:

**Integrity** - when data is semi/weakly structured - it is hard or even impossible to control the state and validity of the data.

**Accessibility and retrieval** - without high-level structure comes the lack of possibility to query the data meaningfully:
 - it may be since our data structure is too low level to express complex queries 
 - handling the complexity of such super detailed and low level queries becomes a problem.
 - it's hard to express search relevancy in a structured-domain related question without the explicit schema definition

 Consequently, we might be forced to ask simple questions only or fall back to client side reasoning functionality.

**Maintenance** -  With very little control over the structure of our data it is hard to alter that structure over time as requirements change. 

### What solution would you like?

The schema defines a specific, high-level structure of data that is enforced across the datasets, providing:
 -  logical integrity guarantees
 -  consistency guarantees 
 -  maintenance simplified and can be automated 
 -  build-in tools for defining relevancy inside the (schema) data-domain

A well-constructed schema enables writing intuitive queries, such queries are seamlessly mapped with how we form them as questions in our mind.

Using a schema sets the ground for performing automated reasoning over the represented data. 

 ----- _Introducing opensearch simple search draft - https://github.com/opensearch-project/sql/issues/763_  ----- 

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by macohen** [comment]
@YANG-DB How do you see the schema here as it relates to index mapping for search applications? Defining a schema per application for e-commerce & document search makes sense and can be accomplished by 1) letting the mapping be autodetected at index time and refining that mapping or 2) defining the mapping intentionally up front while designing your document structure. In details in the https://github.com/opensearch-project/sql/issues/763 proposal, I see that this is all geared towards observability to start. That makes sense given the three pillars (i.e. logs, metrics, traces) and there may be some bootstrapping we could do for search applications, but I assume those schemas would most likely diverge quickly. Do you see this differently?

**Comment by YANG-DB** [comment]
@macohen 
I think that a schema is a common need for every type of domain - the physical schema dictates the index mapping and the logical schema represent the real world entities and relations
Our goal here as a search engine is giving the logical schema for query time questions and having the physical schema for the execution time
This will allow max flexibility during the planing of the relevant domain schema and evolve the logical schema with little physical changes as possible.

Existing open source schema repositories we can review and consider:
 - https://schema.org/
 - https://www.wikidata.org/wiki/Wikidata:Database_reports/EntitySchema_directory
 - https://www.dbpedia.org/about/
 - https://developers.google.com/freebase/guide/basic_concepts

**Comment by msfroh** [comment]
The search apps team reviews this and concluded that it's outside of our current direction.

We might think about trying to define some domain-specific schemata for different search use-cases, but that's probably not something we would address this year.

@YANG-DB -- Are you currently doing or planning anything to support this? Should we move this to another repo?

**Comment by YANG-DB** [comment]
Hi
The simple-schema project is the facility of defining and using a scheme on top of open search.
It will have an API for other plugins to introspect the domain scheme and use this knowledge for their own use case
