### ISSUE TITLE
Release Version 2.5.0

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/search-processor#81]
Release Version 2.5.0

### Preparation

- [x] Assign this issue to a release owner - @mingshl 
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] All the tasks in this issue have been reviewed by the release owner.
- [x] Create, update, triage and label all features and issues targeted for this release with `v2.5.0`.
- [x] Build and publish a plugin build, then update the quickstart script to point to it.
- [x] Cut `2.5` branch

### Pre-Release

- [ ] Increment the version on the parent branch to the next development iteration.
- [x] Gather, review and publish release notes following the [rules](https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md) and back port it to the release branch.[git-release-notes](https://github.com/ariatemplates/git-release-notes) may be used to generate release notes from your commit history.
- [x] Confirm that all changes for `2.5.0` have been merged.

### Release Testing

- [ ] Sanity Testing: Sanity testing *and* fixing of critical issues found.
- [ ] File issues for all intermittent test failures.

### Release

- [ ] Verify all issued labeled for this release are closed or labelled for the next release.
- [ ] Cut release tag after release testing

### Post Release

- [ ] [Optional]Conduct a retrospective, and publish its results.

**Comment by mingshl** [comment]
plugin 2.5.0 build is blocked by opensearch 2.5.0. Will wait until after the 2.5 OpenSearch release next week.

**Comment by mingshl** [comment]
search-processor [2.5.0](https://github.com/opensearch-project/search-processor/releases/tag/2.5.0) is live!
