### ISSUE TITLE
[META] Update config rules for auto organizing label 

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/search-processor#83]
Update config rules for auto organizing the tagged PRs/issues into [categories](https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md#categories):

- [ ] update draft-release-notes-config.yml to categorize as below: 

categories:
  - title: 'Breaking Changes'
    labels:
      - 'Breaking Changes'
  - title: 'Security'
    labels:
      - 'Security'
      - 'security fix'
      - 'security vulnerability'
  - title: 'Features'
    labels:
      - 'Features'
  - title: 'Enhancements'
    labels:
      - 'Enhancements'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'Bug Fixes'
      - 'bug'
  - title: 'Infrastructure'
    labels:
      - 'Infrastructure'
      - 'configuration error'
  - title: 'Documentation'
    labels:
      - 'Documentation'
      - 'documentation'
  - title: 'Maintenance'
    labels:
      - 'Maintenance'
      - 'meta'
      - 'release'
  - title: 'Refactoring'
    labels:
      - 'Refactoring'

**Comment by macohen** [comment]
I like the proposal! For labels, what is the significance of 'meta' and 'release'? Are we inheriting legacy labels from other repos? Would it be better to try to make a 1:1 mapping between title and label wherever possible?

**Comment by noCharger** [comment]
I like the idea of 1:1 mapping and also relying on additional labels to make each PR self-descriptive.

**Comment by mingshl** [comment]
aligned to better make a 1:1 mapping between title and label, will add the according labels once gained maintenance access. 

categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
  - title: 'Security'
    labels:
      - 'security fix'
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Enhancements'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Infrastructure'
    labels:
      - 'infrastructure'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Maintenance'
    labels:
      - 'maintenance'
  - title: 'Refactoring'
    labels:
      - 'refactoring'

**Comment by mingshl** [comment]
Implemented in #84,  closing the issue.
